-- ============================================================
-- SUPABASE DATABASE WEBHOOK → n8n
-- Configurazione via Dashboard (raccomandato)
-- ============================================================
--
-- Dashboard → Integrations → Database Webhooks → Create a new hook
--
--   Name:     new_user_register
--   Table:    profiles
--   Events:   INSERT
--   URL:      https://n8n.pletnusha.xyz/webhook/new-user
--   Method:   POST
--   Headers:
--     Content-Type    application/json
--
-- Il payload inviato da Supabase ha questa struttura:
-- {
--   "type":   "INSERT",
--   "table":  "profiles",
--   "schema": "public",
--   "record": {
--     "id":                  "uuid...",
--     "user_id":             "uuid...",
--     "first_name":          "Mario",
--     "last_name":           "Rossi",
--     "email":               "mario@esempio.it",
--     "generated_password":  "Abc123",
--     "topic_pass":          "principianti/casi/genitivo",
--     "plan":                null,
--     "exercisepaid":        false,
--     "lessonpaid":          false,
--     "n8n_stage":           "new",
--     ...
--   },
--   "old_record": null
-- }
--
-- In n8n accedi ai dati con:
--   $json.body.record.email
--   $json.body.record.first_name
--   ecc.
-- ============================================================
